Remove gds_metrics
This seems to be causing problems building on some people's machines:

```
[...]
Fetching prometheus-client-mmap 0.9.1
Installing prometheus-client-mmap 0.9.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/user/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/prometheus-client-mmap-0.9.1/ext/fast_mmaped_file
/Users/user/.rbenv/versions/2.6.1/bin/ruby -I /Users/user/.rbenv/versions/2.6.1/lib/ruby/2.6.0 -r ./siteconf20190603-657-1ecpyo7.rb extconf.rb
creating Makefile

current directory: /Users/user/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/prometheus-client-mmap-0.9.1/ext/fast_mmaped_file
make "DESTDIR=" clean

current directory: /Users/user/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/prometheus-client-mmap-0.9.1/ext/fast_mmaped_file
make "DESTDIR="
compiling fast_mmaped_file.c
In file included from fast_mmaped_file.c:2:
In file included from /Users/user/.rbenv/versions/2.6.1/include/ruby-2.6.0/ruby.h:33:
/Users/user/.rbenv/versions/2.6.1/include/ruby-2.6.0/ruby/ruby.h:2186:35: error: unused parameter 'allow_transient' [-Werror,-Wunused-parameter]
rb_array_ptr_use_end(VALUE a, int allow_transient)
                                  ^
1 error generated.
make: *** [fast_mmaped_file.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/user/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/prometheus-client-mmap-0.9.1 for inspection.
Results logged to /Users/user/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-17/2.6.0-static/prometheus-client-mmap-0.9.1/gem_make.out

An error occurred while installing prometheus-client-mmap (0.9.1), and Bundler cannot continue.
Make sure that `gem install prometheus-client-mmap -v '0.9.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  gds_metrics was resolved to 0.1.0, which depends on
    prometheus-client-mmap
```

... we never look at the metrics, so it's probably not worth the trouble
investigating why.